REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" save  "C:\Users\samsu\Documents\WatchDue\WatchDue.vcproj"
REM Copmile c file 
"C:\Program Files\ARM\ADSv1_2\Bin\armcc" -O2 -apcs /ropi/rwpi -cpu ARM7EJ-S -o "C:\Users\samsu\Documents\WatchDue\arm\vmmain.o" -c "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\src\vmmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_176X220__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Users\samsu\Documents\WatchDue\include" -I "C:\Users\samsu\Documents\WatchDue\include\service" -I "C:\Users\samsu\Documents\WatchDue\include\component" -I "C:\Users\samsu\Documents\WatchDue\ResID" -I "C:\Users\samsu\Documents\WatchDue\src\app\widget" -I "C:\Users\samsu\Documents\WatchDue\src\app\launcher" -I "C:\Users\samsu\Documents\WatchDue\src\app\wallpaper" -I "C:\Users\samsu\Documents\WatchDue\src\app\screen_lock" -I "C:\Users\samsu\Documents\WatchDue\include\service" -I "C:\Users\samsu\Documents\WatchDue\include\component" -I "C:\Users\samsu\Documents\WatchDue\include\service" -I "C:\Users\samsu\Documents\WatchDue\src\framework" -I "C:\Users\samsu\Documents\WatchDue\src\framework\ui_core\base" -I "C:\Users\samsu\Documents\WatchDue\src\framework\ui_core\mvc" -I "C:\Users\samsu\Documents\WatchDue\src\framework\ui_core\pme" -I "C:\Users\samsu\Documents\WatchDue\src\framework\mmi_core" -I "C:\Users\samsu\Documents\WatchDue\src\ui_engine\vrt\interface" -I "C:\Users\samsu\Documents\WatchDue\src\component" -I "C:\Users\samsu\Documents\WatchDue\src\ui_engine\framework\xml" -I "C:\Users\samsu\Documents\WatchDue" -errors "C:\Users\samsu\Documents\WatchDue\WatchDue.log"
REM Copmile c file 
"C:\Program Files\ARM\ADSv1_2\Bin\armcc" -O2 -apcs /ropi/rwpi -cpu ARM7EJ-S -o "C:\Users\samsu\Documents\WatchDue\arm\WatchDue.o" -c "c:\Users\samsu\Documents\WatchDue\WatchDue.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_176X220__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Users\samsu\Documents\WatchDue\include" -I "C:\Users\samsu\Documents\WatchDue\include\service" -I "C:\Users\samsu\Documents\WatchDue\include\component" -I "C:\Users\samsu\Documents\WatchDue\ResID" -I "C:\Users\samsu\Documents\WatchDue\src\app\widget" -I "C:\Users\samsu\Documents\WatchDue\src\app\launcher" -I "C:\Users\samsu\Documents\WatchDue\src\app\wallpaper" -I "C:\Users\samsu\Documents\WatchDue\src\app\screen_lock" -I "C:\Users\samsu\Documents\WatchDue\include\service" -I "C:\Users\samsu\Documents\WatchDue\include\component" -I "C:\Users\samsu\Documents\WatchDue\include\service" -I "C:\Users\samsu\Documents\WatchDue\src\framework" -I "C:\Users\samsu\Documents\WatchDue\src\framework\ui_core\base" -I "C:\Users\samsu\Documents\WatchDue\src\framework\ui_core\mvc" -I "C:\Users\samsu\Documents\WatchDue\src\framework\ui_core\pme" -I "C:\Users\samsu\Documents\WatchDue\src\framework\mmi_core" -I "C:\Users\samsu\Documents\WatchDue\src\ui_engine\vrt\interface" -I "C:\Users\samsu\Documents\WatchDue\src\component" -I "C:\Users\samsu\Documents\WatchDue\src\ui_engine\framework\xml" -I "C:\Users\samsu\Documents\WatchDue" -errors "C:\Users\samsu\Documents\WatchDue\WatchDue.log"
REM Link app 
"C:\Program Files\ARM\ADSv1_2\Bin\armlink" -o "C:\Users\samsu\Documents\WatchDue\WatchDue.axf"  "C:\Users\samsu\Documents\WatchDue\arm\vmmain.o"  "C:\Users\samsu\Documents\WatchDue\arm\WatchDue.o" -info totals -rwpi -ropi "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\percommon.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\pertcp.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\persensor.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\persmsper.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\perbitstream.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\percontact.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\permms.a" "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armads\persmsmng.a" -errors "C:\Users\samsu\Documents\WatchDue\WatchDue.log"
REM Pack resource to app 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" pack -silent -resolution 176x220 -o "C:\Users\samsu\Documents\WatchDue\WatchDue.pkd" -e AXF "C:\Users\samsu\Documents\WatchDue\WatchDue.vcproj" "C:\Users\samsu\Documents\WatchDue\WatchDue.axf"
REM Add tag infromation 
"C:\Program Files\MRE SDK V3.0.00\tools\PackDigist.exe" "C:\Users\samsu\Documents\WatchDue\WatchDue.vcproj" "Little Dues" "0.1.0" "MacDue" "500" "NotSupportBg" "Not Support rotate" "Little Dues" "Little Dues" "Little Dues" "1234567890" "content" " TCP Sensor SMS(person) BitStream Contact MMS SMSMng" "vxp" "ADS" "PKD" "UnCompress" "NoVPI" "UnAdaptable" "11534556" "SysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  C:\Users\samsu\Documents\WatchDue\arm C:\Users\samsu\Documents\WatchDue\build.log

